server:
  port: 8080

spring:
  application:
    name: payment-gateway-router
  
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.fairoz: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

payment:
  gateways:
    - name: "razorpay"
      weight: 40
      enabled: true
    - name: "payu"
      weight: 35
      enabled: true
    - name: "cashfree"
      weight: 25
      enabled: true
  
  health:
    success-rate-threshold: 90.0
    monitoring-window-minutes: 15
    disable-duration-minutes: 30